name: Deploy Heroku
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        run: make heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
